name: Deploy to Heroku (main)

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'

      - name: Download requirements and install
        run: |
          pip install --download-cache="$HOME/.pip-cache" -r requirements.txt
          pip install $HOME/.pip-cache/*

      - name: Cache dependencies downloaded by pip
        uses: actions/cache@v2
        with:
          path: $HOME/.pip-cache
          with: ${{ hashFiles("$HOME/.pip-cache") }}

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Restore dependencies downloaded by pip
        uses: actions/cache@v2
        with:
          path: $HOME/.pip-cache
          restore: ${{ hashFiles("$HOME/.pip-cache") }}

      - name: Run tests (pytest)
        run: |
          python3 -m pytest -W ignore::DeprecationWarning --no-header -s -v
  
  deploy:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wine-scrapping-api"
          heroku_email: "rodrigues.cassiano2007@gmail.com"
          appdir: "."
          justlogin: true