name: Deploy to Heroku (main)

on:
  [push, pull_request]
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies python 3.10.1
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Running tests
        run: |
          python3 -m pytest -W ignore::DeprecationWarning --no-header -s -v
  
  deploy:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wine-scrapping-api"
          heroku_email: "rodrigues.cassiano2007@gmail.com"
          appdir: "."
          justlogin: true